-- 1. CRIAÇÃO DO BANCO DE DADOS PARA O CINEMA
CREATE DATABASE CINESQL;  -- CRIA A BASE DE DADOS
GO                        -- JÁ DA O COMANDO DE FAZER O PASSO ACIMA IMEDIATAMENTE

-- 2.ENTRAR NO BANCO DE DADOS (ESSENCIAL!)
USE CINESQL;              -- DEPOIS DE CRIADA A BASE DE DADOS ELA VAI SER USADA 
GO                        -- IMEDIATAMENTE PELO USO DO COMANDO GO    

-- CRIAÇÃO DA TABELA
CREATE TABLE FILMES (                        -- OBS: PRIMARY KEY NÃO SE REPETE E O (1,1) É INCREMENTO AUTOMÁTICO
	ID_FILME INT PRIMARY KEY IDENTITY(1,1),  -- CHAVE PRIMARIA QUE AUMENTA DE FORMA CRESCENTE (+1) A CADA CRIAÇÃO
	NOME VARCHAR(100) NOT NULL,              -- NOME NÃO PODE FICAR EM VAZIO E COM TAMANHO MÁXIMO DE 100 CARACTERES
	GENERO VARCHAR(50),                      -- GÊNERO SEGUE A MESMA LÓGICA, MAS COM NO MÁXIMO 50 CARACTERES
	ANO_LANCAMENTO INT,                      -- ANO USA APENAS NÚMEROS INTEIROS (POR MOTIVOS ÓBVIOS)
	DURACAO_MINUTOS INT                      -- DURAÇÃO USARÁ INTEIROS 
);

/*   INSERÇÃO DE TRÊS FILMES:
     Vingadores (Ação, 2012, 143 min)
     O Poderoso Chefão (Drama, 1972, 175 min)
     Matrix (Ficção, 1999, 136 min).               */

INSERT INTO FILMES (NOME, GENERO, ANO_LANCAMENTO, DURACAO_MINUTOS)
VALUES 
('VINGADORES', 'ACAO', 2012, 143),
('O PODEROSO CHEFAO', 'DRAMA', 1972, 175),
('MATRIX', 'FICCAO', 1999, 136);
SELECT * FROM FILMES;