-- 03_Cinesql_Consultas_Complexas.sql
USE CINESQL;
GO 

-- 1. Inserindo os atores
INSERT INTO ATORES (NOME, NACIONALIDADE)
VALUES
('Keanu Reeves', 'Libanês/Canadense'),
('Robert Downey Jr.', 'Americano');
GO

-- 2. Relacionamento na tabela Elenco
-- Aqui irá os IDs. Se Matrix é 1 e Keanu Reeves é 1 ...
INSERT INTO ELENCO (ID_FILME, ID_ATOR, PAPEL)
VALUES 
(3,1, 'Neo'),              -- 3 é Matrix / 1 é Keanu Reeves           SELECT ID_FILME, NOME FROM FILMES;
(1,2, 'Homem de Ferro');   -- 1 é Vingadores / 2 é Robert D. Jr       SELECT ID_ATOR, NOME FROM ATORES;
		
SELECT 
	FILMES.NOME AS FILME,  -- NOME DA TABELA FILMES RECEBE O APELIDO DE FILME 
	ATORES.NOME AS ATOR,   -- NOME DA TABELE ATORES RECEBE O APELIDO DE ATOR
	ELENCO.PAPEL           -- PAPEL DA TABELA ELENCO
FROM FILMES
INNER JOIN ELENCO ON FILMES.ID_FILME = ELENCO.ID_FILME    -- O INNER JOIN JUNTA AS TABELAS E RETORNA APENAS OS REGISTROS
INNER JOIN ATORES ON ELENCO.ID_ATOR = ATORES.ID_ATOR;     -- QUE TÊM A CORRESPONDÊNCIA NAS DUAS TABELAS 

-- ASSIM A CONSULTA CONSEGUE MOSTRAR QUAL ATOR PARTICIPOU DE QUAL FILME E QUAL PERSONAGEM ELE INTERPRETOU



