-- 04. Cinesql_Agregações e filtros avançados
USE CINESQL;
GO

-- RELATÓRIO: QUANTIDADE DE ATORES POR FILME
SELECT 
	F.NOME AS FILME,                                -- NO FROM FILMES TERÁ O APELIDO (ALIAS) "F" E ELENCO "E"
	COUNT(E.ID_ATOR) AS TOTAL_ATORES                -- A CONTAGEM TOTAL SERÁ TOTAL_ATORES
FROM FILMES AS F 
LEFT JOIN ELENCO AS E ON F.ID_FILME = E.ID_FILME
GROUP BY F.NOME;                                     -- GROUP BY CONTA QUANTOS ATORES CADA FILME TEM

-- RELATÓRIO: INVESTIMENTO TOTAL POR GÊNERO
SELECT
	GENERO,
	SUM(PRECO_BASE) AS INVESTIMENTO_TOTAL,
	AVG(PRECO_BASE) AS MEDIA_DE_PRECO
FROM FILMES
GROUP BY GENERO;

-- QUAL O FILME MAIS CARO COM O KEANU REEVES?
SELECT TOP 1
	F.NOME,
	F.PRECO_BASE,
	A.NOME AS ATOR
FROM FILMES F
INNER JOIN ELENCO E ON F.ID_FILME = E.ID_FILME
INNER JOIN ATORES A ON E.ID_ATOR = A.ID_ATOR
WHERE A.NOME = 'Keanu Reeves'
ORDER BY F.PRECO_BASE DESC;


