-- 05. TREINANDO CREATE VIEW

USE CINESQL;
GO

-- CRIANDO O CREATE VIEW QUE FUNCIONA COMO UM ATALHO
CREATE VIEW v_RelatorioCompleto AS 
SELECT
	FILMES.NOME AS FILME,
	ATORES.NOME AS ATOR,
	ELENCO.PAPEL
FROM FILMES
INNER JOIN ELENCO ON FILMES.ID_FILME = ELENCO.ID_FILME
INNER JOIN ATORES ON ELENCO.ID_ATOR = ATORES.ID_ATOR;
GO
-- NA LINHA ABAIXO TESTANDO O CREATE VIEW (v_RelatorioCompleto)
SELECT * FROM v_RelatorioCompleto;